
'use client';

import type { Contract } from '@/lib/types';
import { Badge } from '@/components/ui/badge';
import { format } from 'date-fns';
import { ShieldAlert, ShieldCheck, ShieldHalf } from 'lucide-react';
import type { DetectAndLabelClausesOutput } from '@/ai/schemas/detect-and-label-clauses-schema';
import { getOverallRisk } from '@/lib/utils';
import { Button } from './ui/button';
import { useEffect } from 'react';

type AnalysisReportProps = {
  contract: Contract;
};

const riskLevelToVariant = (
  level: 'High' | 'Medium' | 'Low'
): 'high' | 'medium' | 'low' => {
  return level.toLowerCase() as 'high' | 'medium' | 'low';
};

const RiskIcon = ({ level }: { level: string }) => {
  switch (level) {
    case 'High':
      return <ShieldAlert className="h-5 w-5 text-red-500 flex-shrink-0" />;
    case 'Medium':
      return <ShieldHalf className="h-5 w-5 text-yellow-500 flex-shrink-0" />;
    case 'Low':
      return <ShieldCheck className="h-5 w-5 text-green-500 flex-shrink-0" />;
    default:
      return null;
  }
};

export default function AnalysisReport({ contract }: AnalysisReportProps) {
    
    useEffect(() => {
        // Automatically trigger print dialog when component mounts
        setTimeout(() => window.print(), 500);
    }, []);

  const analysisData = contract.analysis_data as DetectAndLabelClausesOutput | undefined;

  if (!analysisData || contract.status !== 'Analyzed') {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-100 text-gray-800">
        <div className="text-center p-8">
          <h1 className="text-2xl font-bold">Report Not Available</h1>
          <p>The analysis for this contract is incomplete or has errors.</p>
        </div>
      </div>
    );
  }

  const overallRisk = getOverallRisk(analysisData);

  return (
    <div className="bg-white text-gray-800 font-sans p-4 sm:p-8 md:p-12">
        <style jsx global>{`
            @media print {
                .no-print {
                    display: none;
                }
                @page {
                    size: A4;
                    margin: 1.5cm;
                }
                body {
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
            }
        `}</style>

        <header className="flex justify-between items-start pb-6 border-b-2 border-gray-200">
            <div>
                <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight">Contract Analysis Report</h1>
                <p className="text-lg text-gray-500 mt-1">Generated by Legal Decoder AI</p>
            </div>
            <div className="text-right">
                <p className="font-semibold text-gray-700">{contract.name}</p>
                <p className="text-sm text-gray-500">Analyzed on: {format(new Date(contract.analyzedAt), 'MMMM dd, yyyy')}</p>
            </div>
        </header>

        <section className="my-8 grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 rounded-lg bg-gray-50 border border-gray-200 text-center">
                <h3 className="text-md font-semibold text-gray-500 uppercase tracking-wider">Overall Risk</h3>
                 <p className={`text-4xl font-bold mt-2 ${
                    overallRisk === 'High' ? 'text-red-600' :
                    overallRisk === 'Medium' ? 'text-yellow-600' :
                    overallRisk === 'Low' ? 'text-green-600' : 'text-gray-600'
                }`}>{overallRisk}</p>
            </div>
            <div className="p-6 rounded-lg bg-gray-50 border border-gray-200 text-center">
                <h3 className="text-md font-semibold text-gray-500 uppercase tracking-wider">Total Clauses</h3>
                <p className="text-4xl font-bold mt-2 text-gray-800">{contract.clauses}</p>
            </div>
            <div className="p-6 rounded-lg bg-gray-50 border border-gray-200 text-center">
                <h3 className="text-md font-semibold text-gray-500 uppercase tracking-wider">High-Risk Clauses</h3>
                <p className="text-4xl font-bold mt-2 text-red-600">{contract.highRiskClauses}</p>
            </div>
        </section>

        <section className="my-8">
            <h2 className="text-2xl font-bold text-gray-800 mb-6 pb-2 border-b border-gray-200">Clause-by-Clause Breakdown</h2>
            <div className="space-y-6">
                {analysisData.map((clause, index) => (
                    <div key={index} className="p-6 rounded-lg border border-gray-200 bg-white break-inside-avoid">
                         <div className="flex items-center justify-between mb-4">
                            <h3 className="text-xl font-semibold text-gray-800">{clause.clauseType}</h3>
                            <Badge variant={riskLevelToVariant(clause.riskLevel)} className="text-sm py-1">
                                {clause.riskLevel} Risk
                            </Badge>
                         </div>
                         <div className="space-y-4">
                             <div>
                                <h4 className="font-semibold text-gray-600">Plain English Summary</h4>
                                <p className="text-gray-700">{clause.summary}</p>
                             </div>
                             <div>
                                <h4 className="font-semibold text-gray-600">Risk Analysis</h4>
                                <p className="text-gray-700">{clause.riskReason}</p>
                             </div>
                             {(clause.riskLevel === 'High' || clause.riskLevel === 'Medium') && clause.recommendation && (
                                <div>
                                    <h4 className="font-semibold text-gray-600">Recommendation</h4>
                                    <p className="text-gray-700">{clause.recommendation}</p>
                                </div>
                             )}
                         </div>
                    </div>
                ))}
            </div>
        </section>

        <footer className="mt-12 pt-6 border-t-2 border-gray-200 text-center text-xs text-gray-500">
            <p><strong>Disclaimer:</strong> This report is AI-generated and for informational purposes only. It does not constitute legal advice. Please consult with a qualified legal professional for any binding decisions.</p>
            <p className="mt-2">&copy; {new Date().getFullYear()} Legal Decoder. All Rights Reserved.</p>
        </footer>

        <div className="fixed bottom-4 right-4 no-print">
            <Button onClick={() => window.print()}>
                Print or Save as PDF
            </Button>
        </div>
    </div>
  );
}
